apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  name: policies
spec:
  nodeSelector: {}
  byteCode:
    image:
      imagePullSecret:
        namespace: bpfman
        name: openshift-registry
      url: 'default-route-openshift-image-registry.apps.ocp.s7cld.sandbox2542.opentlc.com/bpfman/ebpf-policy:latest'
      imagePullPolicy: Always
  programs:
    - name: block_af_alg_socket
      type: KProbe
      kprobe:
        links:
          - function: security_socket_create
            offset: 0