FROM registry.fedoraproject.org/fedora:latest

RUN dnf install -y \
      gcc \
      glibc-devel \
      glibc-headers \
      kernel-headers \
      make && \
    dnf clean all

WORKDIR /src
COPY exp.c .

RUN gcc -O2 -Wall -Wextra -o dirty-frag-trigger exp.c

ENTRYPOINT [""]